### ISSUE TITLE
Schedules: Empty schedule list

### ISSUE THREAD

**Issue by flourish86** [Icinga/icinga-notifications-web#104] opened 2023-05-25 07:43 UTC
When the list of schedules is empty, the current ui is misleading.

1) The calendar looks as interactive as when there’s a schedule created, but it isn’t. Ideally there should be a notice that the user has to create a schedule first or the calendar should be faded out or not be displayed at all.
2) We should indicate that there’s no schedule, possibly through an empty state notice analogous to the default object list behaviour.

This is how the current view looks, when schedules are empty.
![Screenshot 2023-05-25 at 09 30 54](https://github.com/Icinga/icinga-notifications-web/assets/6977434/abcab59e-1ebc-4173-9b18-762dd29db077)

And when there are some.
![Screenshot 2023-05-25 at 09 37 53](https://github.com/Icinga/icinga-notifications-web/assets/6977434/47d054be-c2f7-4544-bbf2-197863587291)

**Comment by nilmerg** [comment] 2023-05-25 08:38
Misleading, yes. Not displaying the calendar, no, the view is too empty otherwise. Fading it out is an option. I'd also (even without the fading effect) show a notice at the center of the calendar with a clear description how to populate it.

**Comment by nilmerg** [comment] 2024-03-19 08:54
Duplicate of #162

**Closed by nilmerg** 2024-03-19 08:54 UTC
