### ISSUE TITLE
Incident overview breaks a bit when there are too many tags

### ISSUE THREAD

**Issue by martialblog** [Icinga/icinga-notifications-web#265] opened 2024-07-26 07:27 UTC
When I send an event from a source that has a lot of tags to identify an object, the amount of tags breaks the overview a bit:

![screenshot_2024-07-26-091450](https://github.com/user-attachments/assets/32a767e0-8627-451f-be1d-9e632c84f3bc)

![screenshot_2024-07-26-091458](https://github.com/user-attachments/assets/b918e50b-ccdd-4345-a995-41f6046d201a)

![screenshot_2024-07-26-092136](https://github.com/user-attachments/assets/73721ce1-c83f-4142-88b9-586817b8c0c2)

I used a common Kubernetes example (a node in a cluster notifies me about its DiskPressure state)

**Comment by yhabteab** [comment] 2024-07-26 07:32
Duplicate of https://github.com/Icinga/icinga-notifications-web/issues/234

**Closed by yhabteab** 2024-07-26 07:32 UTC
